/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackingdataRouteImport } from './routes/trackingdata'
import { Route as TrackingDothtmlRouteImport } from './routes/tracking[.]html'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as OurStoryRouteImport } from './routes/our-story'
import { Route as FeedingGuidesRouteImport } from './routes/feeding-guides'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'

const TrackingdataRoute = TrackingdataRouteImport.update({
  id: '/trackingdata',
  path: '/trackingdata',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackingDothtmlRoute = TrackingDothtmlRouteImport.update({
  id: '/tracking.html',
  path: '/tracking.html',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const OurStoryRoute = OurStoryRouteImport.update({
  id: '/our-story',
  path: '/our-story',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedingGuidesRoute = FeedingGuidesRouteImport.update({
  id: '/feeding-guides',
  path: '/feeding-guides',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/feeding-guides': typeof FeedingGuidesRoute
  '/our-story': typeof OurStoryRoute
  '/products': typeof ProductsRoute
  '/tracking.html': typeof TrackingDothtmlRoute
  '/trackingdata': typeof TrackingdataRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/feeding-guides': typeof FeedingGuidesRoute
  '/our-story': typeof OurStoryRoute
  '/products': typeof ProductsRoute
  '/tracking.html': typeof TrackingDothtmlRoute
  '/trackingdata': typeof TrackingdataRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/feeding-guides': typeof FeedingGuidesRoute
  '/our-story': typeof OurStoryRoute
  '/products': typeof ProductsRoute
  '/tracking.html': typeof TrackingDothtmlRoute
  '/trackingdata': typeof TrackingdataRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/faq'
    | '/feeding-guides'
    | '/our-story'
    | '/products'
    | '/tracking.html'
    | '/trackingdata'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/faq'
    | '/feeding-guides'
    | '/our-story'
    | '/products'
    | '/tracking.html'
    | '/trackingdata'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/faq'
    | '/feeding-guides'
    | '/our-story'
    | '/products'
    | '/tracking.html'
    | '/trackingdata'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  FeedingGuidesRoute: typeof FeedingGuidesRoute
  OurStoryRoute: typeof OurStoryRoute
  ProductsRoute: typeof ProductsRoute
  TrackingDothtmlRoute: typeof TrackingDothtmlRoute
  TrackingdataRoute: typeof TrackingdataRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trackingdata': {
      id: '/trackingdata'
      path: '/trackingdata'
      fullPath: '/trackingdata'
      preLoaderRoute: typeof TrackingdataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracking.html': {
      id: '/tracking.html'
      path: '/tracking.html'
      fullPath: '/tracking.html'
      preLoaderRoute: typeof TrackingDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-story': {
      id: '/our-story'
      path: '/our-story'
      fullPath: '/our-story'
      preLoaderRoute: typeof OurStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feeding-guides': {
      id: '/feeding-guides'
      path: '/feeding-guides'
      fullPath: '/feeding-guides'
      preLoaderRoute: typeof FeedingGuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  FeedingGuidesRoute: FeedingGuidesRoute,
  OurStoryRoute: OurStoryRoute,
  ProductsRoute: ProductsRoute,
  TrackingDothtmlRoute: TrackingDothtmlRoute,
  TrackingdataRoute: TrackingdataRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
